renamed QA_HOME --> QA_TABLES

diff --git a/install b/install
--- a/install
+++ b/install
@@ -47,14 +47,14 @@ descript()
   echo "                    is assigned, then debug only this one."
   echo "  --force           Force update of the given project."
   echo "  --help            Display usage and exit."
-  echo "  --home=path       Same as QA_HOME."
+  echo "  --home=path       Same as --qa-tables."
   echo "  --lcf=path        Location of .qa-dkrz/config.txt [~]."
   echo "  --link=path       Hard links of external NetCDF installations from the"
   echo "                    directories in 'your-path/${package}/local'."
   echo "                    Shared by all hdf, netcdf, udunits  and zlib."
   echo "  --link_type=path  Same as for 'link' but just for type=netcdf, hdf, zlib, or udunits"
   echo "  --net=no          Disable internet access."
-  echo "  --qa-home=path    Location of the projects tables and external programs."
+  echo "  --qa-tables=path  Location of the projects tables and external programs."
   echo "                    Also for user-modified QA tables."
   echo "  --set-default-project=PROJECT "
   echo "  --show-inst       Display properties of the current installation."
@@ -180,13 +180,13 @@ update()
     fi
   done
 
-  if ! mkdir -p ${QA_HOME}/tables  ; then
-    echo "could not mkdir -p ${QA_HOME}/tables"
+  if ! mkdir -p ${QA_TABLES}/tables  ; then
+    echo "could not mkdir -p ${QA_TABLES}/tables"
     exit 41
   fi
 
-  # note that QA_HOME points to .qa-dkrz wherever it is located
-  rsync -auz --exclude '*~' $QA_SRC/tables ${QA_HOME} &> /dev/null
+  # note that QA_TABLES points to .qa-dkrz wherever it is located
+  rsync -auz --exclude '*~' $QA_SRC/tables ${QA_TABLES} &> /dev/null
 
   return 0
 }
@@ -259,7 +259,7 @@ update_external()
   then
      . ${QA_SRC}/scripts/get_externalSources \
          -P $prj --qa-src=${QA_SRC} \
-         --qa-home=${QA_HOME} --config_file=${CONFIG_FILE} \
+         --qa-tables=${QA_TABLES} --config_file=${CONFIG_FILE} \
          ${isUpdate:+--update} ${isForceUpdate:+--force-update}
 
      test $? -gt 0 && exit 41
@@ -393,13 +393,13 @@ do
             fi
           fi
         elif [ "${OPTNAME}" = HOME ] ; then
-          export QA_HOME=${OPTVAL}
+          export QA_TABLES=${OPTVAL}
         elif [ "${OPTNAME}" = PROJECT ] ; then
           prj="${OPTVAL}"
-        elif [ "${OPTNAME}" = QA_HOME ] ; then
-          export QA_HOME=${OPTVAL}
+        elif [ "${OPTNAME}" = QA_TABLES ] ; then
+          export QA_TABLES=${OPTVAL}
         elif [ "${OPTNAME}" = WORK ] ; then
-          export QA_HOME=${OPTVAL}
+          export QA_TABLES=${OPTVAL}
         fi
         ;;
    \?)  ;;
@@ -408,10 +408,10 @@ done
 
 if [ ${isDisplacedConfigFile} ] ; then
   if [ ! "${displacedConfigFile}" ] ; then
-    if [ ${QA_HOME} ] ; then
-      displacedConfigFile=${QA_HOME}
+    if [ ${QA_TABLES} ] ; then
+      displacedConfigFile=${QA_TABLES}
     else
-      echo "option --cf requires provision of --qa-home"
+      echo "option --cf requires provision of --qa-tables"
       exit 1
     fi
   fi
@@ -512,7 +512,7 @@ do
           PROJECT="${OPTVAL}"
         elif [ "${OPTNAME}" = QA_SRC ] ; then
           export QA_SRC=${OPTVAL}
-        elif [ "${OPTNAME}" = QA_HOME ] ; then
+        elif [ "${OPTNAME}" = QA_TABLES ] ; then
           continue
         elif [ "${OPTNAME}" = SRC ] ; then
           :  # for backward compatibilty
@@ -570,8 +570,8 @@ for pck in $* ; do
     netcdf=${pck}
   elif [ ${PCK:0:7} = UDUNITS ] ; then
     udunits=${pck}
-  elif [ ${PCK:0:7} = QA_HOME ] ; then
-    QA_HOME=${PCK:8}
+  elif [ ${PCK:0:7} = QA_TABLES ] ; then
+    QA_TABLES=${PCK:8}
   elif [ ${PCK:0:10} = PROJECT ] ; then
     PROJECT=${PCK:11}
   else
diff --git a/scripts/getHomePath b/scripts/getHomePath
--- a/scripts/getHomePath
+++ b/scripts/getHomePath
@@ -5,56 +5,56 @@ getHomePath()
   if [ ! ${CONFIG_FILE} ] ; then
      if [ -w ~/.qa-dkrz/config.txt ] ; then
         CONFIG_FILE=~/.qa-dkrz/config.txt
-     elif [ -w ${QA_HOME}/.qa-dkrz/config.txt ] ; then
-        CONFIG_FILE=QA_HOME/.qa-dkrz/config.txt
+     elif [ -w ${QA_TABLES}/.qa-dkrz/config.txt ] ; then
+        CONFIG_FILE=QA_TABLES/.qa-dkrz/config.txt
      else
         CONFIG_FILE=~/.qa-dkrz/config.txt
      fi
   fi
 
   # path to the current user's home
-  export QA_HOME
+  export QA_TABLES
 
-  if [ ${QA_HOME} ] ; then
+  if [ ${QA_TABLES} ] ; then
     # if it is a new path, then adjust the config file
-    . $QA_SRC/scripts/parseConfigFile QA_HOME=${QA_HOME}
+    . $QA_SRC/scripts/parseConfigFile QA_TABLES=${QA_TABLES}
   else
-    # take QA_HOME from the config file, if it exists.
-    if ! . $QA_SRC/scripts/parseConfigFile QA_HOME ; then
+    # take QA_TABLES from the config file, if it exists.
+    if ! . $QA_SRC/scripts/parseConfigFile QA_TABLES ; then
       local dpath
       if [ ${CONDA_QA_PATH} ] ; then
-         dpath="~/.qa_home/QA_HOME"
+         dpath="~/.qa_home/QA_TABLES"
       else
-         dpath=${QA_SRC}/HOME
+         dpath=${QA_SRC}/QA_Tables
       fi
 
-      echo -e "\nPlease, specify variable QA_HOME [default: ${dpath}], " > ${TTY}
-      read -p "the spot for external tables and programs: " QA_HOME 2> ${TTY}
+      echo -e "\nPlease, specify variable QA_TABLES [default: ${dpath}], " > ${TTY}
+      read -p "the spot for external tables and programs: " QA_TABLES 2> ${TTY}
 
-      test ! ${QA_HOME} && QA_HOME=${dpath}
+      test ! ${QA_TABLES} && QA_TABLES=${dpath}
 
       local i
       for i in 1 2 3 ; do
         if [ ${i} -eq 3 ] ; then
-          echo "Could not mkdir QA_HOME=${QA_HOME}."
+          echo "Could not mkdir QA_TABLES=${QA_TABLES}."
           exit 41
         fi
 
-        if mkdir -p ${QA_HOME} &> /dev/null ; then
-          . $QA_SRC/scripts/parseConfigFile QA_HOME=${QA_HOME}
+        if mkdir -p ${QA_TABLES} &> /dev/null ; then
+          . $QA_SRC/scripts/parseConfigFile QA_TABLES=${QA_TABLES}
           break
         fi
 
-        echo "Could not mkdir QA_HOME=${QA_HOME}."
-        QA_HOME=${HOME}/.qa-dkrz
-        read -p "Do you want to try: ${QA_HOME} " QA_HOME 2> ${TTY}
+        echo "Could not mkdir QA_TABLES=${QA_TABLES}."
+        QA_TABLES=${HOME}/.qa-dkrz
+        read -p "Do you want to try: ${QA_TABLES} " QA_TABLES 2> ${TTY}
       done
     fi
 
-    if [ -d $QA_HOME ] ; then
-      if [ ! -w $QA_HOME ] ; then
-        echo "directory $QA_HOME without write permissions,"
-        echo "please, restart with added option --qa-home=path"
+    if [ -d $QA_TABLES ] ; then
+      if [ ! -w $QA_TABLES ] ; then
+        echo "directory $QA_TABLES without write permissions,"
+        echo "please, restart with added option --qa-tables=path"
         exit 41
       fi
     fi
