for travis test

diff --git a/install b/install
--- a/install
+++ b/install
@@ -51,7 +51,7 @@ auto_up()
 
     for key in ${AUTO_OPTS[*]} ; do
        if [ ${key} = ${name} ] ; then
-         . $QA_SRC/scripts/parseConfigFile AUTO-UP_${name}=${value}
+         . ${QA_SRC}/scripts/parseConfigFile AUTO-UP_${name}=${value}
          continue 2  # skip the is-for-all part
        fi
     done
@@ -68,7 +68,7 @@ auto_up()
 
   if [ ${isForAll} = t ] ; then
     for key in ${AUTO_OPTS[*]} ; do
-       . $QA_SRC/scripts/parseConfigFile AUTO-UP_${key}=${value}
+       . ${QA_SRC}/scripts/parseConfigFile AUTO-UP_${key}=${value}
     done
   fi
 
@@ -118,7 +118,7 @@ getCondaPath()
   path=${path%/*}
 
   if ls ${path%/*}/conda-meta/qa-dkrz* &> /dev/null ; then
-    eval ${2}=$path/qa-dkrz
+    eval ${2}=${path}/qa-dkrz
     export CONDA_ENV=t
 
     return 0
@@ -140,25 +140,25 @@ getHomePath()
 
   if [ "${QA_HOME}" ] ; then
     # if it is a new path, then adjust the config file
-    . $QA_SRC/scripts/parseConfigFile QA_HOME=${QA_HOME}
+    . ${QA_SRC}/scripts/parseConfigFile QA_HOME=${QA_HOME}
   else
     # take QA_HOME from the config file, if it exists.
-    if ! . $QA_SRC/scripts/parseConfigFile QA_HOME ; then
+    if ! . ${QA_SRC}/scripts/parseConfigFile QA_HOME ; then
       echo -e "\nPlease, specify variable QA_HOME [default: ${QA_SRC}/HOME], " > ${TTY}
       read -p "the spot for external tables and programs: " QA_HOME 2> ${TTY}
 
       test ! ${QA_HOME} && QA_HOME=${HOME}/.qa-dkrz
 
       if mkdir -p ${QA_HOME} &> /dev/null ; then
-        . $QA_SRC/scripts/parseConfigFile QA_HOME=${QA_HOME}
+        . ${QA_SRC}/scripts/parseConfigFile QA_HOME=${QA_HOME}
       else
         echo  "could not mkdir QA_HOME=${QA_HOME}"
         exit 1
      fi
     fi
 
-    if [ ! -w $QA_HOME ] ; then
-      echo "directory $QA_HOME without write permissions,"
+    if [ ! -w ${QA_HOME} ] ; then
+      echo "directory ${QA_HOME} without write permissions,"
       echo "please, restart with added option --qa-home=path"
       exit 1
     fi
@@ -176,12 +176,12 @@ getRevNum()
 
   if [ $CONDA_ENV ] ; then
     declare -a branch
-    if branch=( $(cat $QA_SRC/install.log 2> /dev/null) ) ; then
+    if branch=( $(cat ${QA_SRC}/install.log 2> /dev/null) ) ; then
       branch[0]=${branch[0]#*=}
       currIdent=${branch[1]#*=}
     fi
   else
-    cd $QA_SRC &> /dev/null
+    cd ${QA_SRC} &> /dev/null
     branch[0]=$(getGitBranch)
     currIdent=$(git log --pretty=format:'%h' -n 1)
     cd - &> /dev/null
@@ -281,9 +281,9 @@ getSrcPath()
     local str=$(ls -l $target 2> /dev/null | awk  '{print $(NF)}')
 
     if [ ${#str} -gt 0 ] ; then
-      str="invalid path=$0"
+      str="invalid path=${0}"
     else
-      str="broken path=$0"
+      str="broken path=${0}"
     fi
 
     echo "${str}"
@@ -326,7 +326,7 @@ saveAsCycle()
       ext=${fx##*.}
 
       if val=$(expr match $ext '\([[:digit:]]\+$\)' 2> /dev/null) ; then
-        test ${val:-0} -gt ${maxVal} && maxVal=$val
+        test ${val:-0} -gt ${maxVal} && maxVal=${val}
       fi
     done
 
@@ -386,7 +386,7 @@ update()
   local packRec
   getRevNum packRev
 
-  . $QA_SRC/scripts/parseConfigFile QA_REVISION${packRev:+=}$packRev
+  . ${QA_SRC}/scripts/parseConfigFile QA_REVISION${packRev:+=}${packRev}
 
   return 0
 }
@@ -395,9 +395,9 @@ update_external()
 {
   test ${isInternet:-t} = f && return
 
-  if ! . $QA_SRC/scripts/parseConfigFile QA_LAST_UPDATE=${today} \
+  if ! . ${QA_SRC}/scripts/parseConfigFile QA_LAST_UPDATE=${today} \
         || [ ${isUpdateQA:-f} = t ]; then
-    if [ ${isCondaUpdate:-t} = t -a -w ${QA_SRC} ] ; then
+    if [ ${isCondaUpdate:-t} = t -a -w "${QA_SRC}" ] ; then
       # look for a new conda-built package
 #      local tmp
 #      declare -a tmp
@@ -427,7 +427,7 @@ update_external()
     if [ "${prj}" != CF ] ; then
       # check it here in order to prevent an update of the config-file in case
       # that the installation failed or war terminated.
-      . $QA_SRC/scripts/parseConfigFile ${prj}_LAST_UPDATE
+      . ${QA_SRC}/scripts/parseConfigFile ${prj}_LAST_UPDATE
       eval lastUpdate=\${prj}_LAST_UPDATE
 
       if [ "${lastUpdate}" != ${today} -o ${isUpdateQA:-f} = t ]; then
@@ -438,14 +438,14 @@ update_external()
 
          test $? -gt 0 && exit 1
 
-         . $QA_SRC/scripts/parseConfigFile ${prj}_LAST_UPDATE=${today}
+         . ${QA_SRC}/scripts/parseConfigFile ${prj}_LAST_UPDATE=${today}
       fi
     fi
 
     test "${PROJECT_AS}" && break
   done
 
-  if ! . $QA_SRC/scripts/parseConfigFile CF_LAST_UPDATE=${today} \
+  if ! . ${QA_SRC}/scripts/parseConfigFile CF_LAST_UPDATE=${today} \
         || [ ${isUpdateQA:-f} = t ]; then
       ${QA_SRC}/scripts/get_cfconventions \
          --qa_path=${QA_SRC} ${DEBUG} \
@@ -459,10 +459,10 @@ update_external()
 update_QA()
 {
   if [ ${isInternet:-t} = t ] ; then
-    if ! . $QA_SRC/scripts/parseConfigFile QA_LAST_UPDATE=${today} \
+    if ! . ${QA_SRC}/scripts/parseConfigFile QA_LAST_UPDATE=${today} \
           || [ ${isUpdateQA:-f} = t ]; then
       if [ ! -f ${QA_SRC}/.ignore_GitHub ] ; then
-        cd $QA_SRC
+        cd ${QA_SRC}
 
         # is qa-dkrz going to change?
         local qa_dkrzDate=$(ls -l \
@@ -485,13 +485,13 @@ update_QA()
     fi
   fi
 
-  if ! mkdir -p $QA_HOME/tables  ; then
-    echo "could not mkdir -p $QA_HOME/tables"
+  if ! mkdir -p ${QA_HOME}/tables  ; then
+    echo "could not mkdir -p ${QA_HOME}/tables"
     exit 1
   fi
 
   # note that QA_HOME points to .qa-dkrz wherever it is located
-  rsync -auz --exclude '*~' $QA_SRC/tables $QA_HOME &> /dev/null
+  rsync -auz --exclude '*~' $QA_SRC/tables ${QA_HOME} &> /dev/null
 
   return
 }
@@ -649,12 +649,12 @@ getHomePath
 #  auto_up ${autoUpArgs[*]}
 #fi
 
-if ! . $QA_SRC/scripts/parseConfigFile \
+if ! . ${QA_SRC}/scripts/parseConfigFile \
              DEFAULT_PROJECT${DEF_PRJ:+=}${DEF_PRJ} ; then
   # get or set value.
   # note: is set to the defaultProject value at initialisation of the config file,
   #       required here for longer existing config files without entry
-  . $QA_SRC/scripts/parseConfigFile DEFAULT_PROJECT=${defaultProject}
+  . ${QA_SRC}/scripts/parseConfigFile DEFAULT_PROJECT=${defaultProject}
 fi
 
 test ! "$project" && project=(${DEFAULT_PROJECT#*=})
@@ -679,6 +679,6 @@ if [ "${project[0]}" = NONE ] ; then
    exit
 fi
 
-exec $QA_SRC/scripts/install.sh ${debug} --pack=${package} \
+exec ${QA_SRC}/scripts/install.sh ${debug} --pack=${package} \
 ${isContinueLog:+--continue_log} ${pcks} \
 ${PROJECT_AS:+--PROJECT_AS=${PROJECT_AS}} ${coll[*]}
