install triggered by qa-dkrz.py and more

diff --git a/install b/install
--- a/install
+++ b/install
@@ -62,7 +62,8 @@ descript()
   echo "                    Also for user-modified QA tables."
   echo "  --ship=/path      Prepare the current QA-DKRZ installation for shipping."
   echo "  --show-inst       Display properties of the current installation."
-  echo "  --unship          See ReadTheDocs:installation."
+  echo "  --
+  See ReadTheDocs:installation."
   echo "  --up[date]        Update external packages/tables from respective repository."
   echo "                    Note: not for netCDF, HDF5, udunits2 or zlib."
   echo "  --up              Update the qa-dkrz package when installed by conda."
@@ -70,6 +71,14 @@ descript()
   echo "                    --uf and any --uXXX_FYYY is valid; num in days with default [1]"
   echo ""
   echo '  projects-name(s)   At present CF, CMIP5/6, [CORDEX] and HAPPI.'
+
+  return
+}
+
+freeze()
+{
+    test "${CFG_UPDATE}" != frozen && . $QA_SRC/scripts/parseConfigFile UPDATE=frozen
+    exit 0
 }
 
 getSrcPath()
@@ -161,18 +170,19 @@ saveAsCycle()
 
 ship()
 {
-    local ov=$1
+    local pth=$1
 
-    if [ ! ${ov} ] ; then
-      echo "--ship=path requires a path"
-      exit
+    if [ ! ${pth} ] ; then
+      echo "--ship requires a path"
+      exit 41
     fi
 
-    if ! mkdir -p $ov ; then
-      exit
+    if ! mkdir -p $pth ; then
+      echo "--ship=${pth}: could not mkdir/open path"
+      exit 41
     fi
 
-    if [ ${OPTVAL} ] ; then
+    if [ ${pth} ] ; then
         test -f $QA_SRC/.ship-qa-config.tx && \rm -f $QA_SRC/.ship-qa-config.txt
         . $QA_SRC/scripts/parseConfigFile --ship
 
@@ -180,42 +190,42 @@ ship()
         if [ ${CONDA_QA_PATH} ] ; then
           local bp=${CONDA_QA_PATH%/bin/conda}
           cd ${bp%/*} &> /dev/null
-          echo  "tar cvf ${ov}/QA-DKRZ.tar ${bp##*/} "
+          echo  "tar cf ${pth}/QA-DKRZ.tar ${bp##*/} "
           progress_wheel &
           job_id=$!
-          tar cvf ${ov}/QA-DKRZ.tar ${bp##*/}
+          tar cf ${pth}/QA-DKRZ.tar ${bp##*/}
           kill -TERM $job_id
         else
           cd ${QA_SRC%/*} &> /dev/null
-          echo -e "\rtar cvf ${ov}/QA-DKRZ.tar QA-DKRZ "
+          echo -e "\rtar cf ${pth}/QA-DKRZ.tar QA-DKRZ "
           progress_wheel &
           job_id=$!
-          tar cvf ${ov}/QA-DKRZ.tar QA-DKRZ
+          tar cf ${pth}/QA-DKRZ.tar QA-DKRZ
           kill -TERM $job_id
         fi
 
         . $QA_SRC/scripts/parseConfigFile QA_TABLES
         cd ${QA_TABLES%/*} &> /dev/null
-        echo -e "\rtar cvf ${ov}/QA-DKRZ.tar QA_TABLES "
+        echo -e "\rtar cf ${pth}/QA-DKRZ.tar $QA_TABLES "
         progress_wheel &
         job_id=$!
-        tar rvf ${ov}/QA-DKRZ.tar QA_TABLES
+        tar rf ${pth}/QA-DKRZ.tar $QA_TABLES
         kill -TERM $job_id
 
         if . $QA_SRC/scripts/parseConfigFile PrePARE ; then
           local bp=${PrePARE%/envs/cmor/bin/PrePARE}
           cd ${bp%/*} &> /dev/null
-          echo -e "\rtar rvf ${ov}/QA-DKRZ.tar PrePARE-package"
+          echo -e "\rtar rf ${pth}/QA-DKRZ.tar PrePARE-package"
           progress_wheel &
           job_id=$!
           if [ CONDA_QA_PATH} ] ; then
-             tar rvf ${ov}/QA-DKRZ.tar ${bp##*/}
+             tar rf ${pth}/QA-DKRZ.tar ${bp##*/}
           else
              tar --exclude="${bp##*/}/envs/qa-dkrz" --exclude="${bp##*/}/qa-dkrz*" \
-               rvf ${ov}/QA-DKRZ.tar ${bp##*/}
+               rf ${pth}/QA-DKRZ.tar ${bp##*/}
           fi
 
-          tar rvf ${ov}/QA-DKRZ.tar ${bp##*/}
+          tar rf ${pth}/QA-DKRZ.tar ${bp##*/}
           kill -TERM $job_id
         fi
     else
@@ -268,7 +278,6 @@ unship()
 {
    test $PWD != $QA_SRC && cd $QA_SRC &> /dev/null
 
-
    # find the root of a conda based tree
    local j k base_path x_itm
    x_itm=( ${PWD//\// } )
@@ -293,7 +302,7 @@ unship()
    fi
 
    local line
-   mkdir ~/.qa-dkrz
+   mkdir ~/.qa-dkrz 2> /dev/null
    echo -n '' > ~/.qa-dkrz/config.txt
 
    while read line ; do
@@ -301,33 +310,36 @@ unship()
    done < .ship-qa-config.txt
 
    \rm -f .ship-qa-config.txt
-   exit
+
+   return
 }
 
 update()
 {
   local prj
 
-  for prj in $* ; do
-    if ! . ${QA_SRC}/scripts/inqRunEnv ${prj} ; then
-      isForceUpdate=t  # look for updates
-      break
-    fi
-  done
-  test ${DEBUG} && end_of_inq=t  # just a mark
+  if [ ${isForce:-f} = f ] ; then
+    for prj in $* ; do
+      if ! . ${QA_SRC}/scripts/inqRunEnv ${prj} ; then
+        isForce=t  # search updates
+        break
+      fi
+    done
+    test ${DEBUG} && end_of_inq=t  # just a mark
+  fi
 
   # search updates after a specified number of days; default: once a day
   if [ ${CONDA_QA_PATH} ] ; then
       test ! ${CONDA_QA_ENV} && \
         . ${QA_SRC}/scripts/parseConfigFile CONDA_QA_ENV
 
-      if [ ${isForceUpdate:-f} = t ] || \
+      if [ ${isForce:-f} = t ] || \
            ! . ${QA_SRC}/scripts/parseConfigFile NEXT_QA_UPDATE --inquire
       then
         if update_CONDA "${CONDA_QA_NAME}" "${CONDA_QA_CHANNELS}" \
                       "${CONDA_QA_PATH}"   "${CONDA_QA_ENV:-qa-dkrz}" ; then
 
-          . ${QA_SRC}/scripts/parseConfigFile NEXT_QA_UPDATE ${isForceUpdate:+--force}
+          . ${QA_SRC}/scripts/parseConfigFile NEXT_QA_UPDATE ${isForce:+--force}
           . ${QA_SRC}/scripts/parseConfigFile CONDA_QA_ENV=${CONDA_QA_ENV:-qa.dkrz}
 
           # updates the QA_CONDA_REVISION entry in the config-file
@@ -335,20 +347,22 @@ update()
         fi
       fi
   elif [ -d ${QA_SRC}/.git ] ; then
-     test ${isForceUpdate} && \
+     test ${isForce} && \
           $QA_SRC/scripts/getVersion --force ${DEBUG} &> /dev/null
 
      test -w ${QA_SRC} && update_QA_SRC
   fi
 
-  # now for non-QA-DKRZ tables and programs
-  if ! update_external $prj ; then
-    return $?
-  fi
+  # now for project related tables and programs
+  for prj in $* ; do
+    if ! update_external $prj ; then
+      return $?
+    fi
+  done
 
   if ! mkdir -p ${QA_TABLES}/tables  ; then
-    echo "could not mkdir -p ${QA_TABLES}/tables"
-    exit 41
+    echo "failure: mkdir -p ${QA_TABLES}/tables"
+    exit 1
   fi
 
   # note that QA_TABLES points to .qa-dkrz wherever it is located
@@ -374,7 +388,7 @@ update_CONDA()
   if [ ! -w "${QA_SRC}" ] ; then
     return
     #echo "no write-permission for ${QA_SRC}"
-    #exit 41
+    #exit 1
   elif [ ${action} = update ] ; then
     # look for a new conda-built package
     echo "searching ${conda_name} updates" > ${TTY}
@@ -426,20 +440,20 @@ update_external()
   # check it here in order to prevent an update of the config-file in case
   # that the installation failed or was terminated.
 
-  if [ ${isForceUpdate:-f} = t ] || \
+  if [ ${isForce:-f} = t ] || \
          ! . ${QA_SRC}/scripts/parseConfigFile NEXT_${prj}_UPDATE --inquire
   then
      . ${QA_SRC}/scripts/get_externalSources \
          -P $prj --qa-src=${QA_SRC} \
          --qa-tables=${QA_TABLES} --config_file=${CONFIG_FILE} \
-         ${isUpdate:+--update} ${isForceUpdate:+--force-update}
+         ${isUpdate:+--update} ${isForce:+--force-update}
 
-     test $? -gt 0 && exit 41
+     test $? -gt 0 && exit 1
 
      local nextUpdate
      eval nextUpdate=\$NEXT_${prj}_UPDATE
 
-  . ${QA_SRC}/scripts/parseConfigFile NEXT_${prj}_UPDATE ${isForceUpdate:+--force}
+  . ${QA_SRC}/scripts/parseConfigFile NEXT_${prj}_UPDATE ${isForce:+--force}
   fi
 
   return 0
@@ -448,7 +462,7 @@ update_external()
 update_QA_SRC()
 {
   if [ ${INTERNET:-t} = t ] ; then
-    if [ ${isForceUpdate:-f} = t ] || \
+    if [ ${isForce:-f} = t ] || \
            ! . ${QA_SRC}/scripts/parseConfigFile NEXT_QA_UPDATE --inquire
     then
       if [ ! -f ${QA_SRC}/.ignore_GitHub ] ; then
@@ -494,7 +508,7 @@ update_QA_SRC()
 
         test ${isRestart} -eq 1 && exec ${QA_SRC}/install ${initialArgs[*]}
 
-        . ${QA_SRC}/scripts/parseConfigFile NEXT_QA_UPDATE ${isForceUpdate:+--force}
+        . ${QA_SRC}/scripts/parseConfigFile NEXT_QA_UPDATE ${isForce:+--force}
 
         # update of the QA_GitHub_REVISION entry in the config-file
         $QA_SRC/scripts/getVersion --config-file=$CONFIG_FILE --force ${DEBUG} \
@@ -531,6 +545,8 @@ if [ $# -gt 0 ] ; then
       sArgs[${i}]=--${sArgs[${i}]}
     elif [ "${A:0:5}" = DEBUG ] ; then
       sArgs[${i}]=--${sArgs[${i}]}
+    elif [ "${A}" = FORCE ] ; then
+      sArgs[${i}]=--${sArgs[${i}]}
     elif [ "${A:0:6}" = FREEZE ] ; then
       sArgs[${i}]=--${sArgs[${i}]}
     elif [ "${A:0:4}" = HELP ] ; then
@@ -539,9 +555,13 @@ if [ $# -gt 0 ] ; then
       sArgs[${i}]=--${sArgs[${i}]}
     elif [ "${A:0:6}" = ONLY-Q ] ; then
       sArgs[${i}]=--${sArgs[${i}]}
+    elif [ "${A:0:4}" = SHIP  ] ; then
+      sArgs[${i}]=--${sArgs[${i}]}
     elif [ "${A:0:3}" = SRC  ] ; then
       sArgs[${i}]=--${sArgs[${i}]}
     elif [ "${A:0:2}" = UP ] ; then
+      sArgs[${i}]=--${sArgs[${i}]}
+    elif [ "${A}" = UNFREEZE ] ; then
       sArgs[${i}]=--${sArgs[${i}]}
     fi
 
@@ -582,27 +602,29 @@ do
 done
 
 if ! . $QA_SRC/scripts/getConfigFile ; then
-  isPostFreeze=t
+  isFreeze=t
 fi
 
 # is it in a conda built?
 . ${QA_SRC}/scripts/getCondaPath
 
-# convert AUTO_UPDATE --> UPDATE=auto
+# convert AUTO_UPDATE --> UPDATE=daily
 if . ${QA_SRC}/scripts/parseConfigFile AUTO_UPDATE ; then
    . ${QA_SRC}/scripts/parseConfigFile AUTO_UPDATE=delete
-   . ${QA_SRC}/scripts/parseConfigFile UPDATE=auto
+   . ${QA_SRC}/scripts/parseConfigFile UPDATE=daily
 fi
 
-# delete obsolete names
+# delete obsolete config-options
 . ${QA_SRC}/scripts/parseConfigFile QA_REVISION=delete
 . ${QA_SRC}/scripts/parseConfigFile DEFAULT_PROJECT=delete
 
-. ${QA_SRC}/scripts/parseConfigFile UPDATE
-
-if [ "${UPDATE}" != frozen ] ; then
-    isUpdate=t
+if ! . ${QA_SRC}/scripts/parseConfigFile UPDATE ; then
+  # after the first installation or when UPDATE is missing
+  isFreeze=t
 fi
+
+CFG_UPDATE=$UPDATE
+UPDATE=
 
 OPTIND=
 while getopts BdhT:-: option ${sArgs[*]}
@@ -620,21 +642,11 @@ do
         OPTNAME=${UOPTARG%%=*}
         test ${OPTARG/=/} = ${OPTARG} && OPTVAL=''
 
-        if [ "${UOPTARG:0:7}" = AUTO_UP ] ; then
-            OV=$OPTVAL}
-            tr_option OV
-            . ${QA_SRC}/scripts/parseConfigFile UPDATE
-
-            # enable
-            if [ "${UPDATE}" != 'auto' ] ; then
-                . ${QA_SRC}/scripts/parseConfigFile UPDATE=auto
-            fi
-            isUpdate=t
-            continue
-        elif [ "${OPTNAME}" = BUILD ] ; then
+        if [ "${OPTNAME}" = BUILD ] ; then
           isBuild=t
         elif [ "${OPTNAME}" = COMPILE ] ; then
           FORCE_COMPILE=-B
+          isForce=t
         elif [ "${OPTNAME}" = CONDA_BUILD ] ; then
           isCondaBuild=t
         elif [ "${OPTNAME}" = CONDA_CMOR_ENV -o "${OPTNAME}" = CCE ] ; then
@@ -654,22 +666,13 @@ do
           . ${QA_SRC}/scripts/parseConfigFile CONDA_QA_PATH=${OPTVAL}
 
         elif [ "${OPTNAME}" = FORCE ] ; then
-          test ! -d ~/.qa-dkrz && mkdir ~/.qa-dkrz
-
-          CONFIG_FILE=  # unset
-          . $QA_SRC/scripts/getConfigFile
-          # . $QA_SRC/scripts/parseConfigFile UPDATE=daily
-
-          isForceUpdate=t
+          isForce=t
         elif [ "${OPTNAME}" = FREEZE ] ; then
           isFreeze=t
         elif [ "${OPTNAME}" = HELP ] ; then
           descript
           exit 41
         elif [ "${OPTNAME}" = HOME ] ; then
-          continue
-        elif [ "${OPTNAME}" = INQ_TABLES ] ; then
-          isInqTables=t
           continue
         elif [ "${UOPTARG:0:4}" = LINK ] ; then
           isLink=t
@@ -687,25 +690,37 @@ do
 #          . ${QA_SRC}/scripts/parseConfigFile INTERNET=${OPTVAL}
         elif [ "${OPTNAME:0:6}" = ONLY_Q ] ; then
           :  # for backward compatibilty
-        elif [ "${OPTNAME}" = POST_FREEZE ] ; then
-          isPostFreeze=t
         elif [ "${OPTNAME}" = PROJECT -a ${#OPTVAL} -gt 0 ] ; then
           projects[${#projects[*]}]="${OPTVAL}"
         elif [ "${OPTNAME}" = QA_SRC ] ; then
           export QA_SRC=${OPTVAL}
         elif [ "${OPTNAME}" = QA_TABLES ] ; then
           continue
+#    elif [ "${OPTNAME}" = SET_DEFAULT_PROJECT ] ; then
+#    test "${OPTVAL}" && . ${QA_SRC}/scripts/parseConfigFile DEFAULT_PROJECT=${OPTVAL}
+#    continue
         elif [ "${OPTNAME}" = SHIP ] ; then
-          ship ${OPTVAL} # function
-          exit
+          shipOpt=${OPTVAL}
+          isShip=t
         elif [ "${OPTNAME}" = SRC ] ; then
           :  # for backward compatibilty
+        elif [ "${OPTNAME}" = UNFREEZE ] ; then
+          isFreeze=
+          isUnfreeze=t
         elif [ "${OPTNAME}" = UNSHIP ] ; then
           unship  # function
-          exit
+          . ${QA_SRC}/scripts/parseConfigFile UPDATE=frozen
+          exit 0
         elif [ "${OPTNAME:0:2}" = UP ] ; then
-          isUpdate=t
-          test "${OPTVAL}" && . ${QA_SRC}/scripts/parseConfigFile UPDATE=${OPTVAL}
+          if [ "${OPTVAL}" = FREEZE ] ; then
+            isFreeze=t
+          else
+            isUpdate=t
+            if [ "${OPTVAL}" ] ; then
+               . ${QA_SRC}/scripts/parseConfigFile UPDATE=${OPTVAL}
+               UPDATE=${OPTVAL}
+            fi
+          fi
           continue
         elif [ "${OPTNAME:0:1}" = U ] ; then
           name_0=${OPTNAME%%_*}
@@ -713,7 +728,7 @@ do
 
           if [ "${OPTNAME:0:2}" = UF \
                -o \( "${name_0:0:1}" = U -a "${name_1:0:1}" = F \) ] ; then
-            next_period=( ${next_period[*]} ${OPTVAL//,/ } )
+            next_update_cycle=( ${next_update_cycle[*]} ${OPTVAL//,/ } )
             continue
           fi
         elif [ "${OPTNAME}" = WORK ] ; then
@@ -739,14 +754,22 @@ done
 
 shift $(( $OPTIND - 1 ))
 
-if [ ${isFreeze:-f} = t -a ${isPostFreeze:-f} = f ] ; then
-    . $QA_SRC/scripts/parseConfigFile UPDATE=frozen
-    exit
+if [ ${isUnfreeze} ] ; then
+    test ${UPDATE} = frozen && UPDATE=daily
+
+    # could be empty for a single update
+    test ${UPDATE} && . $QA_SRC/scripts/parseConfigFile UPDATE=$UPDATE
 fi
 
-if [ "${UPDATE}" = frozen ] ; then
-  echo "currently frozen; use install --force ... to re-enable"
-  exit
+if [ "${CFG_UPDATE}" = frozen ] ; then
+  if [ ! \( ${isForce:-f} = f -o ${isShip:-f} = f \) ] ; then
+    echo "currently frozen; use install --unfreeze to re-enable updates unconditionally"
+    echo "                  or with --force for a single update, but keeping frozen enabled."
+    exit 1
+  fi
+elif [ ${isUpdate:-f} = f -a ${CFG_UPDATE:-f} != f ] ; then
+  isUpdate
+  UPDATE=${CFG_UPDATE}
 fi
 
 if [ ! "${TTY}" ] ; then
@@ -768,71 +791,66 @@ for pck in $* ; do
   elif [ ${PCK:0:7} = QA_TABLES ] ; then
     QA_TABLES=${PCK:8}
   else
-    coll[${#coll[*]}]=$pck  # collect projects names
+    # collect projects names
+    prj=
     for p in ${valid_projects[*]} ; do
       if [ $p = $pck ] ; then
-         projects[${#projects[*]}]=$pck
+         prj=$pck
+         break
       fi
     done
+
+    if [ ${prj} ] ; then
+       coll[${#coll[*]}]=$prj
+       projects[${#projects[*]}]=$prj
+    fi
   fi
 done
 
+# make all by default
+test ${#projects[*]} -eq 0 && projects=( ${valid_projects[*]} )
+
 if ! . ${QA_SRC}/scripts/getTablesPath ; then
-  exit 41
+  exit 1
 fi
 
-# inquire usually from ~/.qa-dkrz/config.txt;
-if [ ${isInqTables} ] ; then
-  for project in ${projects[*]} ; do
-    if ! . ${QA_SRC}/scripts/inqRunEnv --inquire ${project} ; then
-      exit 41
+if [ ${isUpdate} ] ; then
+
+  # also ensures that all names in the config.files are defined in this program
+  if [ ! ${isCondaBuild} ] ; then
+    if [ ! ${isBuild} ] ; then
+      update ${projects[*]}
     fi
-  done
 
-  exit 0
-fi
-
-# also ensures that all names in the config.files are defined in this program
-if [ ! ${isCondaBuild} ] ; then
-  if [ ! ${isBuild} ] ; then
-    update ${projects[*]}
-  fi
-
-  if [ ${#next_period[*]} -gt 0 ] ; then
-    NEXT_VARIABLES=(QA CONDA_CMOR)
-    for(( i=0 ; i < ${#projects[*]} ; ++i )) ; do
-      NEXT_VARIABLES[${#NEXT_VARIABLES[*]}]=${projects[i]}
-    done
-
-    if [ ${#next_period[*]} = 1 -a ${next_period[0]} = ${next_period[0]//=/} ] ; then
-       for nv in ${NEXT_VARIABLES[*]} ; do
-         # apply to all
-         . ${QA_SRC}/scripts/parseConfigFile NEXT_${nv}_UPDATE --set_frequency=${next_period[0]}
-       done
-    else
-      # individual settings
-      for dn in ${next_period[*]} ; do
-        for nv in ${NEXT_VARIABLES[*]} ; do
-          if [ ${dn%=*} = ${nv} ] ; then
-        . ${QA_SRC}/scripts/parseConfigFile NEXT_${nv}_UPDATE --set_frequency=${dn#*=}
-          fi
-        done
+    if [ ${#next_update_cycle[*]} -gt 0 ] ; then
+      NEXT_U_CYCLE=(QA CONDA_CMOR)
+      for(( i=0 ; i < ${#projects[*]} ; ++i )) ; do
+        NEXT_U_CYCLE[${#NEXT_U_CYCLE[*]}]=${projects[i]}
       done
+
+      if [ ${#next_update_cycle[*]} = 1 -a ${next_update_cycle[0]} = ${next_update_cycle[0]//=/} ] ; then
+         for nv in ${NEXT_U_CYCLE[*]} ; do
+           # apply to all
+           . ${QA_SRC}/scripts/parseConfigFile NEXT_${nv}_UPDATE --set_frequency=${next_update_cycle[0]}
+         done
+      else
+        # individual settings
+        for dn in ${next_update_cycle[*]} ; do
+          for nv in ${NEXT_U_CYCLE[*]} ; do
+            if [ ${dn%=*} = ${nv} ] ; then
+          . ${QA_SRC}/scripts/parseConfigFile NEXT_${nv}_UPDATE --set_frequency=${dn#*=}
+            fi
+          done
+        done
+      fi
     fi
   fi
-
-  if [ ${isPostFreeze} ] ; then
-      . $QA_SRC/scripts/parseConfigFile UPDATE=frozen
-  fi
-
-  # miniconda built executables
-  test ${FORCE_COMPILE:-f} = f -a ${#CONDA_QA_PATH} -gt 0 && exit
 fi
 
-#if [ ${#projects[*]} -eq 0 ] ; then
-#   echo 'install requires at least a PROJECT name'
-#   exit 0
-#fi
+if [ ${isShip} ] ; then
+   ship ${shipOpt}
+   exit 41
+fi
 
 if [ ${isBuild:-f} = t -a ${isLink:-f} = t ] ; then
   echo "scripts/install.sh: options --build and --link exclude each other"
@@ -844,10 +862,12 @@ else
   pcks=
 fi
 
-if [ ${isPostFreeze} ] ; then
-  . $QA_SRC/scripts/parseConfigFile UPDATE=frozen
-fi
+test ${isFreeze} && freeze  # and exit
 
+if [ ${#projects[*]} -eq 0 ] ; then
+   echo "$0 ${initialArgs[*]}:  at least one PROJECT name is required"
+   exit 1
+fi
 
 exec ${QA_SRC}/scripts/install.sh ${debug} --pack=${package} \
 ${isContinueLog:+--continue_log} ${pcks} \
