CMIP6 next generation

diff --git a/scripts/get_externalSources b/scripts/get_externalSources
--- a/scripts/get_externalSources
+++ b/scripts/get_externalSources
@@ -1,40 +1,52 @@
-cf()
+ges_cf()
 {
    local org=http://cfconventions.org
 
-   cf_html
+   ges_cf_html
 
    return $?
 }
 
-cf_html()
+ges_cf_html()
 {
+  local status=0
+
   # htmnl page containing access to cf related tables
   local html=standard-names.html
   wget -q -N $org/$html
 
   if [ ! -f ${file} ] ; then
     err[${#err[*]}]="failed wget -N $org/$html"
-    return 1
+    return 41
   fi
 
-  parse_html "Standard Name Table" xml
-  parse_html "Area Type Table" xml
-  parse_html "Standardized Region List" html
+  if ! ges_parse_html "Standard Name Table" xml ; then
+    return $?
+  fi
+
+  if ! ges_parse_html "Area Type Table" xml ; then
+    return $?
+  fi
+
+  if ! ges_parse_html "Standardized Region List" html ; then
+    return $?
+  fi
 
   return 0
 }
 
-convert_html2txt()
+ges_convert_html2txt()
 {
   if [ "${2}" = "Standardized Region List" ] ; then
-    convert_html2txt_region "$1"
+    if ! ges_convert_html2txt_region "$1" ; then
+       return $?
+    fi
   fi
 
   return 0
 }
 
-convert_html2txt_region()
+ges_convert_html2txt_region()
 {
   local htmlFile=${1}
   local txtFile=CF_${1%html}txt
@@ -61,7 +73,7 @@ convert_html2txt_region()
 
       # rm leading
       test "${line:i:1}" = ' ' && continue
-      test "${line:i:6}" = '</div>' && return
+      test "${line:i:6}" = '</div>' && return 0
       if [ "${line:i:1}" = '<' ] ; then
         echo "${txt}" >> ${txtFile}
         txt=
@@ -75,16 +87,16 @@ convert_html2txt_region()
   return 0
 }
 
-convert_xml2txt()
+ges_convert_xml2txt()
 {
   if [ "${2}" = "Area Type Table" ] ; then
-    convert_xml2txt_area "$1"
+    ges_convert_xml2txt_area "$1"
   fi
 
   return 0
 }
 
-convert_xml2txt_area()
+ges_convert_xml2txt_area()
 {
   local xmlFile=${1}
   local txtFile=CF_${1%xml}txt
@@ -120,7 +132,7 @@ convert_xml2txt_area()
   return 0
 }
 
-parse_html()
+ges_parse_html()
 {
   local table="$1"
   local type=$2
@@ -144,103 +156,53 @@ parse_html()
 
   if [ ${#cf_table_name} -eq 0 ] ; then
     err[${#err[*]}]="grep failed to find string ${table} in file $html"
-    return 1
+    return 41
   fi
 
   if [ ${#cf_table_name} -gt 0 ] ; then
     if ! wget -q -N $org/${cf_table_name} ; then
       err[${#err[*]}]="failed wget -q -N $org/${cf_table_name}"
-      return 1
+      return 41
     fi
   fi
 
   if [ ${cf_table_name##*.} = html ] ; then
-    convert_html2txt ${cf_table_name##*/} "${table}"
+    ges_convert_html2txt ${cf_table_name##*/} "${table}"
   elif [ ${cf_table_name##*.} = xml ] ; then
-    convert_xml2txt ${cf_table_name##*/} "${table}"
+    ges_convert_xml2txt ${cf_table_name##*/} "${table}"
   fi
 
   return $?
 }
 
-cmip6()
+ges_cmip6()
 {
-   # pwd is QA_HOME
+   local status=0
 
-   if ! . $QA_SRC/scripts/parseConfigFile XLSX2CSV  ; then
-     if ! xlsx2csv ; then
-       return 1
+   if [ ! ${XLSX2CSV} ] ; then
+     if ! ges_xlsx2csv ; then
+        status=$?
      fi
    fi
 
-   if ! cmip6_mip ; then
-     return 1
-   fi
-
-   . $QA_SRC/scripts/parseConfigFile CONDA_FOR_CMOR3
-
-   if [ $? -gt 0 ] ; then
-      if [ ${CONDA_PATH:-f} = t ] ; then
-        CONDA_FOR_CMOR3=${CONDA_PATH}
-        . $QA_SRC/scripts/parseConfigFile CONDA_FOR_CMOR3=${CONDA_FOR_CMOR3}
-      else
-        # required for CMOR from LLNL; parseConfigFile is called in make_miniconda
-        if [ ${CONDA_FOR_CMOR3:-f} = f -o ! -d ${CONDA_FOR_CMOR3} ] ; then
-          make_miniconda
-        fi
-      fi
-   fi
-
-   if ! cmip6_cmor ; then
-     return 1
-   fi
-
-   return 0
-}
-
-cmip6_mip()
-{
-   local curPWD=$(pwd)
-
-   mkdir -p ${QA_HOME}/tables/projects/CMIP6
-   cd ${QA_HOME}/tables/projects/CMIP6 &> /dev/null
-
-   wget -l1 -N -np  \
-      http://proj.badc.rl.ac.uk/svn/exarch/CMIP6dreq/tags/latest/dreqPy/docs/CMIP6_MIP_tables.xlsx \
-      &>> log_cmip6_tables.txt
-
-   if [ $? -gt 0 ] ; then
-      err[${#err[*]}]="wget CMIP6_MIP_tables.xlsx from http://proj.badc.rl.ac.uk"
-      cd - &> /dev/null
-      return 1
-   fi
-
-   # location of extracted csv table sheets: [~/.qa-dkrz/tables/projects/CMIP6]
-   $QA_HOME/xlsx2csv/xlsx2csv.py -a -d '|' -l '\n' \
-       CMIP6_MIP_tables.xlsx CMIP6_MIP_tables
-
-   # the CMIP6 json files
-   if [ -d CMIP6_CVs ] ; then
-     cd CMIP6_CVs
-
-     if [ "$(getGitBranch)" != master ] ; then
-       git checkout master &> /dev/null
+   if [ ! \( "${LAST_CMIP6_UPDATE}" = $today -a ${isForceUp:-f} = f \) ] ; then
+     if ! ges_cmip6_mip ; then # non-cmor tables
+       status=$?
      fi
 
-     git fetch && git reset --hard origin/master &>> log_cmip6_tables.txt
-   else
-     git clone https://github.com/WCRP-CMIP/CMIP6_CVs &>> log_cmip6_tables.txt
+     if ! ges_cmip6_conda ; then
+          status=$?
+     fi
+
+     if ! ges_cmip6_cmor ; then
+        status=$?
+     fi
    fi
 
-   if [ $? -gt 0 ] ; then
-      err[${#err[*]}]="git failed for CMIP6_CVs from https://github.com/WCRP-CMIP"
-      return 1
-   fi
-
-   return 0
+   return $status
 }
 
-cmip6_cmor()
+ges_cmip6_cmor()
 {
    # Clone the CMIP6 table to your working directory.
    # Disable SSL verification (firewall only).
@@ -261,48 +223,146 @@ cmip6_cmor()
      git clone https://github.com/PCMDI/cmip6-cmor-tables.git &> log_cmip6-cmor.txt
    fi
 
-   if [ $? -gt 0 ] ; then
+   local status=$?
+
+   if [ $status -gt 0 ] ; then
      cat log_cmip6-cmor-tables.txt > ${TTY}
-   fi
-
-   # install cmor, it will also install cdms2.
-   test ! ${CONDA_FOR_CMOR3} && \
-     . $QA_SRC/scripts/parseConfigFile CONDA_FOR_CMOR3
-
-   # environment already installed?
-   if [ -d ${CONDA_FOR_CMOR3}/envs/cmor ] ; then
-     source ${CONDA_FOR_CMOR3}/envs/cmor/bin/activate cmor &> /dev/null
-
-     ${CONDA_FOR_CMOR3}/bin/conda install -c conda-forge -c pcmdi -c uvcdat cmor \
-          | tee -a log_cmip6-cmor.txt 2> ${TTY}
-
-     source ${CONDA_FOR_CMOR3}/envs/cmor/bin/deactivate &> /dev/null
-   else
-      ${CONDA_FOR_CMOR3}/bin/conda create -n cmor \
-           -c conda-forge -c pcmdi -c uvcdat cmor \
-          | tee -a log_cmip6-cmor.txt > ${TTY}
-   fi
-
-   if [ $? -gt 0 ] ; then
-      err[${#err[*]}]="could not ${CONDA_FOR_CMOR3}/bin/conda install -c conda-forge -c pcmdi -c uvcdat cmor"
-      return 1
    fi
 
    cd - &> /dev/null
 
-   . $QA_SRC/scripts/parseConfigFile \
-        PrePARE=${QA_HOME}/miniconda/envs/cmor/bin/PrePARE.py
-
-   return 0
+   return $status
 }
 
-cordex()
+ges_cmip6_conda()
+{
+  local conda_path
+  local conda_env
+  local action isNewConda
+
+  if [ ${PrePARE} ] ; then
+    action=update
+    conda_path=${PrePARE%/*}
+  elif [ ${CONDA_QA_PATH} ] ; then
+    # existing miniconda for the cmor installation?
+    action=create
+    conda_path=${CONDA_QA_PATH}
+  else
+    # e.g. for a conda-less instantiation;
+    # sets conda_path
+    action=create
+#    ges_make_miniconda
+
+    conda_path=${QA_HOME}/miniconda
+    isNewConda=t
+  fi
+
+  if [ ${action} = create ] ; then
+     local prompt_text
+     echo -e "\nCMIP6 requires conda for running CMOR." > ${TTY}
+     if [ ${isNewConda} ] ; then
+       prompt_text=" <yes: in ${conda_path%/bin}, [no]>: "
+     else
+       echo -e "\nDifferent installation modes are available:" > ${TTY}
+       echo    " <a> environment of its own (original) " > ${TTY}
+       echo    " <b> environment of qa-dkrz " > ${TTY}
+       echo    " <c> a separate miniconda instantiated in the user-space" > ${TTY}
+       echo    " <no> exit"
+       prompt_text="    Select: <a, b, c: in [${QA_HOME}/miniconda], or user-defined-path, [no]>: "
+     fi
+
+     local quest
+
+     while : ; do
+       read -p "${prompt_text}"  quest 2> ${TTY}
+
+       case ${quest:0:1} in
+         ( n |  '') exit 41  ;;
+         (       a) conda_env=cmor  ;;
+         (       b) conda_env=qa-dkrz  ;;
+         (       c) conda_path=${QA_HOME}/miniconda
+                    isNewConda=t
+                    ;;
+         *) if [ ${quest:0:1} != '/' ] ; then
+              echo "Please, provide absolute path (in case of no typo)" > ${TTY}
+              continue
+            else
+              conda_path=${quest}
+              isNewConda=t
+            fi
+            ;;
+       esac
+
+       break
+     done
+  fi
+
+  conda_path=${conda_path%/miniconda*}/miniconda
+
+  test ${isNewConda} && ges_make_miniconda ${conda_path}
+
+  if [ ${conda_path} ] ; then
+    if update_CONDA "${CONDA_CMOR_NAME}" "${CONDA_CMOR_CHANNELS}" \
+                    "${conda_path}" ${conda_env:-cmor} ${action} ; then
+
+      . ${QA_SRC}/scripts/parseConfigFile LAST_CONDA_CMOR_UPDATE=$today
+      . ${QA_SRC}/scripts/parseConfigFile CONDA_CMOR_ENV=${conda_env:-cmor}
+      return 0
+    fi
+  fi
+
+  return 41
+}
+
+ges_cmip6_mip()
+{
+   local curPWD=$(pwd)
+
+   mkdir -p ${QA_HOME}/tables/projects/CMIP6
+   cd ${QA_HOME}/tables/projects/CMIP6 &> /dev/null
+
+   wget -l1 -N -np  \
+      http://proj.badc.rl.ac.uk/svn/exarch/CMIP6dreq/tags/latest/dreqPy/docs/CMIP6_MIP_tables.xlsx \
+      &>> log_cmip6_tables.txt
+
+   if [ $? -gt 0 ] ; then
+      err[${#err[*]}]="wget CMIP6_MIP_tables.xlsx from http://proj.badc.rl.ac.uk"
+      cd - &> /dev/null
+      return 41
+   fi
+
+   # location of extracted csv table sheets: [~/.qa-dkrz/tables/projects/CMIP6]
+   ${XLSX2CSV} -a -d '|' -l '\n' CMIP6_MIP_tables.xlsx CMIP6_MIP_tables
+
+   # the CMIP6 json files
+   if [ -d CMIP6_CVs ] ; then
+     cd CMIP6_CVs
+
+     if [ "$(ges_getGitBranch)" != master ] ; then
+       git checkout master &> /dev/null
+     fi
+
+     git fetch && git reset --hard origin/master &>> log_cmip6_tables.txt
+   else
+     git clone https://github.com/WCRP-CMIP/CMIP6_CVs &>> log_cmip6_tables.txt
+   fi
+
+   local status=$?
+
+   if [ $status -gt 0 ] ; then
+      err[${#err[*]}]="git failed for CMIP6_CVs from https://github.com/WCRP-CMIP"
+   fi
+
+   return $status
+}
+
+ges_cordex()
 {
    local status
 
    if ! mkdir -p $QA_HOME/tables/projects/$prj ; then
      mkdir -p $1
-     return 1
+     return 41
    fi
 
    cd $QA_HOME/tables/projects/$prj
@@ -310,7 +370,7 @@ cordex()
    if [ -d IS-ENES-Data.github.io ] ; then
      cd IS-ENES-Data.github.io
 
-     if [ "$(getGitBranch)" != master ] ; then
+     if [ "$(ges_getGitBranch)" != master ] ; then
        git checkout master &> /dev/null
      fi
 
@@ -333,147 +393,88 @@ cordex()
      err[${#err[*]}]="git failed for IS-ENES-Data.github.io"
    fi
 
-   return
+   return ${status}
 }
 
-make_miniconda()
+ges_getGitBranch()
 {
-   local quest
+   git branch | grep '*' | awk '{print $2}'
+   return 0
+}
 
-   # test for an existing PrePARE executable
-   local prg
-   if prg=$( which conda 2> /dev/null) ; then
-     prg=${prg%/*}
-     prg=${prg%/*}
-     CONDA_FOR_CMOR3=$prg
+ges_make_miniconda()
+{
+   test ${PrePARE} && return 0
 
-     local i fs t0 t1
-     declare -a fs times
-     fs=( $( find $prg -name "PrePARE.py" ) )
-     t0=$( ls -l --time-style='+%s' ${fs[0]} | awk '{print $6}')
-     PrePARE=${fs[0]}
+   local path quest
+   path=${1%/bin}
+   path=${path%/miniconda}
 
-     for(( i=1 ; i < ${#fs[*]} ; ++i )) ; do
-       t1=$( ls -l --time-style='+%s' ${fs[0]} | awk '{print $6}')
-       if [ $t1 -gt $t0 ] ; then
-          t0=t1
-          PrePARE=${fs[i]}
-       fi
-     done
+   # look for a conda installation. Is conda in PATH?
+   echo    "miniconda: 'yes' would approve the '3-clause BSD License'!" > ${TTY}
 
-     if [ ${PrePARE} ] ; then
-        local foundP=t
+   local isRead
 
-        echo -e "\nFound PrePARE.py in your conda environment." > ${TTY}
-        echo -e -n "Do you want to use this?\nNot recommended; will not search updates" > ${TTY}
-        while :  ; do
-          read -p " <y[es], [no]>: "  quest 2> ${TTY}
-          case $quest in
-             ( y | yes ) foundP=t ; break ;;
-             ( no | '' ) foundP=f ; break ;;
-                      *)  ;;
-          esac
-        done
+   while : ; do
+     read -p "  <yes: in ${path}/miniconda, r: read license, [no]>: " \
+          quest 2> ${TTY}
 
-        if [ $foundP = t ] ; then
-          . $QA_SRC/scripts/parseConfigFile CONDA_FOR_CMOR3=${CONDA_FOR_CMOR3}
-          . $QA_SRC/scripts/parseConfigFile PrePARE=${PrePARE}
-          return 0
-        fi
+     case $quest in
+       ( y | yes)  ;;
+       ( no | '') return 41  ;;
+       r) isRead=t ;;
+       *) continue ;;
+     esac
+
+     if mkdir -p ${path} ; then
+        cd ${path}
+     else
+        return 41
      fi
-   fi
 
-   # no conda in PATH
-   if [ ! -d ${QA_HOME}/miniconda ] ; then
-     echo -e "\nRunning CMOR requires conda, which will be installed" > ${TTY}
-     echo    "regardless of any other conda instance. " > ${TTY}
-     echo    "Saying 'yes' or specificaion of a path would approve the '3-clause BSD License'! ." > ${TTY}
+     if [ ! -f Miniconda-latest-Linux-x86_64.sh ] ; then
+       wget -l1 -N -np \
+          https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
+     fi
 
-     local conda_path isRead
-
-     while : ; do
-       read -p "  <yes [in ${QA_HOME}/miniconda], your-path, read license, [no]>: " \
-            quest 2> ${TTY}
-
-       test "${quest:0:4}" = read && quest=r
-       isRead=f
-
-       case $quest in
-         ( y | yes) conda_path=${QA_HOME}/miniconda  ;;
-         ( no | '') exit 1  ;;
-         r) isRead=t ;;
-         *) conda_path=${quest} ;;
-       esac
-
-       if [ ${conda_path:-f} != f -o ${isRead} = t ] ; then
-         if [ ! -f Miniconda-latest-Linux-x86_64.sh ] ; then
-           wget -l1 -N -np \
-              https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
-         fi
-
-         if [ ${isRead} = t ] ; then
-            bash Miniconda-latest-Linux-x86_64.sh  > ${TTY} << EOF
+     if [ ${isRead:-f} = t ] ; then
+       bash Miniconda-latest-Linux-x86_64.sh  > ${TTY} << EOF
 
 no
 EOF
-            continue
-         fi
-       fi
-
-       if [ ${conda_path:-f} ] ; then
-         test ${conda_path##*/} = miniconda && \
-            conda_path=${conda_path%/*}
-
-         if [ ! -d ${conda_path}/miniconda ] ; then
-            if ! bash Miniconda-latest-Linux-x86_64.sh -b -p ${conda_path}/miniconda \
-                 > ${TTY} ; then
-
-              if [ ! -w ${conda_path} ] ; then
-                 err[${#err[*]}]="failed bash Miniconda-latest-Linux-x86_64.sh -b -p ${conda_path}/miniconda"
-                 return 1
-              fi
-            fi
-         fi
-
-         break
-       fi
-     done
-
-     if [ ! -w ${conda_path} ] ; then
-        err[${#err[*]}]="Sorry, no write permission for ${conda_path}; Exit"
-        return 1
+       continue
      fi
 
-     CONDA_FOR_CMOR3=$conda_path/miniconda
+     if ! bash Miniconda-latest-Linux-x86_64.sh -b -p ${conda_path} \
+           &> /dev/null ; then
 
-     if [ ! -x "${CONDA_FOR_CMOR3/bin/conda}" ] ; then
-        err[${#err[*]}]="Installation of conda failed; please try manually; Exit"
-        return 1
-     fi
+        if [ ! -w ${conda_path/miniconda} ] ; then
+           err[${#err[*]}]="failed bash Miniconda-latest-Linux-x86_64.sh -b -p ${conda_path}/miniconda"
+           return 41
+        fi
+        fi
 
-   else
-     CONDA_FOR_CMOR3=${QA_HOME}/miniconda
-   fi
-
-   . $QA_SRC/scripts/parseConfigFile CONDA_FOR_CMOR3=${CONDA_FOR_CMOR3}
+     break
+   done
 
    return 0
 }
 
-xlsx2csv()
+ges_xlsx2csv()
 {
-   if [ -f $QA_HOME/xlsx2csv/xlsx2csv.py ] ; then
-      . $QA_SRC/scripts/parseConfigFile XLSX2CSV=$QA_HOME/xlsx2csv/xlsx2csv.py
-   else
+   local xc=$QA_HOME/xlsx2csv/xlsx2csv.py
+
+   if [ ! -f $xc ] ; then
       git clone http://github.com/dilshod/xlsx2csv &>> log_install_xlsx2csv.txt
 
       if [ $? -gt 0 ] ; then
         err[${#err[*]}]="git failed for xlsx2csv"
-        return 1
+        return 41
       fi
-
-      . $QA_SRC/scripts/parseConfigFile XLSX2CSV=$QA_HOME/xlsx2csv/xlsx2csv.py
    fi
+
+    # new or restored entry in the config file
+   . $QA_SRC/scripts/parseConfigFile XLSX2CSV=$xc
 
    return 0
 }
@@ -499,48 +500,62 @@ do
          QA_SRC=${OPTARG##*=}
        fi
        ;;
-   \?) exit 1 ;;
+   \?) echo "get_externalSources: undefined option $option"
+       return 41 ;;
   esac
 done
 
 if [ ! ${QA_HOME} ] ; then
   echo "could not cd ${HOME}"
-  return 1
+  return 41
 fi
 
 cd $QA_HOME &> /dev/null
 
 # search for updates only once a day
-today=$( date '+%Y%m%d' )
+test !${today} && today=$( date '+%Y%m%d' )
 
 # Note that CF may-be stand-alone or together with another project
-. $QA_SRC/scripts/parseConfigFile CF_LAST_UPDATE
-if [ ! \( "${CF_LAST_UPDATE}" = $today -a ${isForceUp:-f} = f \) ] ; then
-   if cf ; then
-     . $QA_SRC/scripts/parseConfigFile CF_LAST_UPDATE=$today
-   fi
+if [ ! \( "${LAST_CF_UPDATE}" = $today -a ${isForceUp:-f} = f \) ] ; then
+  #. $QA_SRC/scripts/parseConfigFile LAST_CF_UPDATE
+  #if [ ! \( "${LAST_CF_UPDATE}" = $today -a ${isForceUp:-f} = f \) ] ; then
+     if ges_cf ; then
+       . $QA_SRC/scripts/parseConfigFile LAST_CF_UPDATE=$today
+     else
+       return 41
+     fi
+  #fi
 fi
 
-. $QA_SRC/scripts/parseConfigFile ${prj}_LAST_UPDATE
-eval pLU=\$${prj}_LAST_UPDATE
+ges_pLU=LAST_${prj}_UPDATE
+test "${!ges_pLU}" = $today -a ${isForceUp:-f} = f && return 0
 
-test "${pLU}" = $today -a ${isForceUp:-f} = f && return 0
+#if [ ! \( "${!ges_pLU}" = $today -a ${isForceUp:-f} = f \) ] ; then
+#  . $QA_SRC/scripts/parseConfigFile ${!pLU}
+
+#  test "${!pLU}" = $today -a ${isForceUp:-f} = f && return 0
+#fi
+status=0
 
 if [ "$prj" = CORDEX ] ; then
-  cordex
+  if ! ges_cordex ; then
+    status=$?
+  fi
 elif [ "$prj" = CMIP6 ] ; then
-  cmip6
+  if ! ges_cmip6 ; then
+    status=$?
+  fi
 fi
-
 
 if [ ${#err[*]} -gt 0 ] ; then
    for(( k=0 ; k < ${#err[*]} ; ++k )) ; do
       echo -e "${err[k]}"
    done
 
-   exit 1
+   return 41
 fi
 
-. $QA_SRC/scripts/parseConfigFile ${prj}_LAST_UPDATE=${today}
+test ${status} -eq 0 && \
+   . $QA_SRC/scripts/parseConfigFile LAST_${prj}_UPDATE=${today}
 
 return 0
diff --git a/scripts/qa-dkrz b/scripts/qa-dkrz
--- a/scripts/qa-dkrz
+++ b/scripts/qa-dkrz
@@ -1511,52 +1511,6 @@ getFilenameBase()
   return
 }
 
-getHomePath()
-{
-  setKWL CONFIG_FILE=~/.qa-dkrz/config.txt
-
-  # path to the current user's home
-  export QA_HOME
-
-  if [ "${QA_HOME}" ] ; then
-    # if it is a new path, then adjust the config file
-    . $QA_SRC/scripts/parseConfigFile QA_HOME=${QA_HOME}
-  else
-    # take QA_HOME from the config file, if it exists.
-    if ! . $QA_SRC/scripts/parseConfigFile QA_HOME ; then
-      echo -e "\nPlease, specify QA_HOME [default: ${QA_SRC}/HOME], " > ${TTY}
-      read -p "the spot for external tables and programs: " QA_HOME 2> ${TTY}
-
-      test ! ${QA_HOME} && QA_HOME=${QA_SRC}/HOME
-
-      local i
-      for i in 1 2 3 ; do
-        if [ ${i} -eq 3 ] ; then
-          echo "Could not mkdir QA_HOME=${QA_HOME}."
-          exit 1
-        fi
-
-        if mkdir -p ${QA_HOME} &> /dev/null ; then
-          . $QA_SRC/scripts/parseConfigFile QA_HOME=${QA_HOME}
-          break
-        fi
-
-        echo "Could not mkdir QA_HOME=${QA_HOME}."
-        QA_HOME=${HOME}/.qa-dkrz
-        read -p "Do you want to try: ${QA_HOME} " QA_HOME 2> ${TTY}
-      done
-    fi
-
-    if [ ! -w $QA_HOME ] ; then
-      echo "directory $QA_HOME without write permissions,"
-      echo "please, restart with added option --qa-home=path"
-      exit 1
-    fi
-  fi
-
-  return
-}
-
 ##//! Get the name of a host ready for a start of the \a qaExecutor
 
 ##/*!
@@ -2530,109 +2484,6 @@ getSelectedPaths()
   return
 }
 
-getQA_SRC()
-{
-  # extract the path to the root of the QA package
-
-  # is it in a conda built?
-  local x_conda=${0%/qa-dkrz/scripts/qa-dkrz}
-  if [ ${x_conda##*/} = opt ] ; then
-    x_conda=${x_conda%/opt}
-    if [ -d $x_conda/opt/qa-dkrz ] ; then
-       setKWL CONDA_ENV=t
-       setKWL QA_SRC=$x_conda/opt/qa-dkrz
-       return
-    fi
-  fi
-
-  local target isInvalid
-
-  if [ ${1:0:1} = '/' ] ; then
-    target=$1
-  else
-    target=$(pwd)/$1
-  fi
-
-  if [ -h $target ] ; then
-
-    # get the link
-    local link=$(ls -l $target | awk  '{print $(NF)}')
-
-    # link is relative, so make it absolute
-    test ${link:0:1} != '/' && link=${target%/*}/${link}
-
-    getQA_SRC ${link}
-
-  elif [ -f $target ] ; then
-
-    # a real instance, at first resolve .. and .
-    # works also for . or .. in the middle of the path
-
-    local xname=${target##*/}
-    target=${target%/*}  # remove the name of the script
-
-    local arr=( ${target//\// } )
-
-    local i j sz
-    sz=${#arr[*]}
-
-    for(( i=1 ; i < sz ; ++i )) ; do
-
-      if [ "${arr[i]}" = '.' ] ; then
-        unset arr[i]
-      elif [ "${arr[i]}" = '..' ] ; then
-        j=$((i-1))
-
-        # this takes into account adjacent . and/or .. with any depth
-        while [ ! ${arr[j]} ] ; do
-          j=$((j-1))
-        done
-        unset arr[j]
-        unset arr[i]
-      fi
-    done
-
-    # get rid of empty items
-    arr=( ${arr[*]} )
-
-    sz=${#arr[*]}
-
-    local tmp
-    for(( i=0 ; i < sz ; ++i )) ; do
-      tmp=${tmp}/${arr[i]}
-
-      if [ -f ${tmp}/.install_configure ] ; then
-        QA_SRC=$tmp
-        break
-      fi
-    done
-
-    test $i -eq $sz && isInvalid=t
-  else
-    isInvalid=t
-  fi
-
-  if [ ${isInvalid:-f} = t ] ; then
-
-    local str=$(ls -l $target 2> /dev/null | awk  '{print $(NF)}')
-
-    if [ ${str} ] ; then
-      str="invalid path=$0"
-    else
-      str="broken path=$0"
-    fi
-
-    std_out "${0##*/}::getQA_SRC():"
-    std_out "$str"
-    std_out flush
-    exit 1
-  fi
-
-  setKWL QA_SRC=${QA_SRC}
-
-  return
-}
-
 has()
 {
   local c i j t
@@ -2701,16 +2552,14 @@ init()
   NO_STATUS=f
   isTPUT=f
 
-  # sets: CONDA_ENV, QA_SRC
-  getQA_SRC $0
-
   test ${QA_EXAMPLE:-f} = t && initExample
 
   # note: if not --example, then example_args is empty
   basic_args=( ${example_args[*]} -E_QA_SRC=${QA_SRC} )
 
   # sets: QA_HOME, CONFIG_FILE
-  getHomePath
+  . ${QA_SRC}/scripts/getHomePath
+
   basic_args=( ${basic_args[*]} -E_QA_HOME=${QA_HOME} )
 
   # configuration
@@ -2740,50 +2589,52 @@ init()
 
   # package update requested and required?
   if [ ! ${UPDATE} ] ; then
-    if . $QA_SRC/scripts/parseConfigFile \
-         AUTO_UPDATE${AUTO_UP:+=}${AUTO_UP} ; then
+    if . $QA_SRC/scripts/parseConfigFile AUTO_UPDATE${AUTO_UP:+=}${AUTO_UP} ; then
       UPDATE=t
     fi
   fi
 
-  if [ ${UPDATE:-f} = t ] ; then
+  local prj=${PROJECT_AS:-${PROJECT}}
+
+  if [ ${UPDATE:-f} = t -o ${ONLY_INSTALL:-f} = t ] ; then
     # checksum of current qa-dkrz
     local md5_0
     md5_0=$( md5sum ${QA_SRC}/scripts/qa-dkrz | awk '{print $1}' )
 
-#    if . $QA_SRC/scripts/parseConfigFile AUTO_UPDATE ; then
-#    else
-#       local quest
-#       echo -e "\n Do you want to update external programs and/or tables? " > $TTY
-#       echo -n "Saying 'yes' would always automatically search updates. <yes, [no]: >"  > $TTY
+    if ${QA_SRC}/install ${TTY:+-T } ${TTY} ${INSTALL_ARGS//,/ } ${prj} ; then
 
-#       while : ; do
-#         read -p "<yes, [no], or auto-up>: " quest 2> $TTY
-
-#         case ${quest:0:4} in
-#           ( y | yes )  isInstall=t ; break ;;
-#           ( no | '' ) isInstall=f
-#                      . $QA_SRC/scripts/parseConfigFile AUTO_UPDATE=disable
-#                      break ;;
-#                auto ) INSTALL_ARGS="--auto-up,${INSTALL_ARGS}" ; isInstall=t ; break  ;;
-#                    *) ;;
-#         esac
-#       done
-#    fi
-
-    if ${QA_SRC}/install ${TTY:+-T } ${TTY} ${INSTALL_ARGS//,/ } \
-                           PROJECT_AS=${PROJECT_AS} ${PROJECT} ; then
+        test ${ONLY_INSTALL:-f} = t && exit 0
 
         local md5_1
         md5_1=$( md5sum ${QA_SRC}/scripts/qa-dkrz | awk '{print $1}' )
 
         test ${md5_0} != ${md5_1} && \
             exec ${QA_SRC}/scripts/qa-dkrz ${initial_params[*]}
+
     else
+       test $? -eq 41 & exit  # silently
+
        # could not make the executable for the given project
-       std_out flush "could not make: install ${PROJECT}"
+       std_out flush "could not install ${prj}"
        exit 1
     fi
+
+    test ${ONLY_INSTALL} && exit
+
+  elif ! . $QA_SRC/scripts/inqRunEnv --read-only ${prj} ; then
+      # get the state of the current installation: read config-file
+      if [ $? > 9 -a ${UPDATE:-f} = f ] ; then
+        local installArg="--install${prj:+=${prj}}"
+
+        if [ "${prj}" = CMIP6 ] ; then
+          echo -e "\nFile ~/.qa-dkrz/config.txt has no entry for CMIP6."
+        else
+          echo -e "\nThe state of file ~/.qa-dkrz/config.txt does not allow to run the task."
+        fi
+
+        echo "Please, run: $0 ${installArg} ${comLineArgs[*]}"
+        exit 1
+      fi
   fi
 
   # expand comma-sep-list to arrays
@@ -3172,8 +3023,6 @@ initTables()
   else
     initTcat CF_CHECK_LIST=${CF_CHECK_LIST}
   fi
-
-# get CF tables
 
   return
 }
@@ -5163,16 +5012,30 @@ wait_fnct()
 ##main()
 ##{
 ######## main ############
+
+comLineArgs=( $* )
+
 umask 002
+export CONFIG_FILE=$HOME/.qa-dkrz/config.txt
+
+mkdir -p ${HOME}/.qa-dkrz
+
+THIS=${0%/*}
+cd ${THIS} &> /dev/null
+THIS=$(pwd)
+cd - &> /dev/null
+
+test ${THIS##*/} = scripts && THIS=${THIS%/*}
+# resolve symbolic links
+. ${THIS}/scripts/getSrcPath
+
+# is it in a conda built?
+. ${QA_SRC}/scripts/getCondaPath
 
 initial_params=( $* )
 
 # store the tty, if any
 if tty -s ; then TTY=$(tty) ; fi
-
-# test for nohup
-
-#sleep 10
 
 QA_CONFIG=qa-config
 QA_FILE_EXECUTER=qa-exec-check
diff --git a/scripts/qa-exec-check b/scripts/qa-exec-check
--- a/scripts/qa-exec-check
+++ b/scripts/qa-exec-check
@@ -209,69 +209,6 @@ clearProcPool()
   fi
 }
 
-convertCMOR_out2QA()
-{
-  local i flag_txt n isFirst isTxt sz
-  isFirst=t
-  isTxt=f
-
-  for((i=0 ; i < ${#annot_CMOR_LLNL[*]} ; ++i )) ; do
-     flag_txt="FLAG-BEGL1-CMOR3_${#annot_CMOR_LLNL[i]}:CAPT-BEG"
-
-     # take into account that the last char may-be the '.'
-     # of the first and only sentence.
-     sz=$(( ${#annot_CMOR_LLNL[i]} -1 ))
-
-     for(( n=0 ; n < sz ; ++n )) ; do
-       # convert \n to blanks
-       if [ "${annot_CMOR_LLNL[i]:n:1}" = ';' ] ; then
-         flag_txt="${flag_txt},"
-         continue
-       elif [ "${annot_CMOR_LLNL[i]:n:2}" = '\n' ] ; then
-         n=$((n+1))
-         flag_txt="${flag_txt} "
-         continue
-       fi
-
-       # find the first sentence
-       if [ ${isFirst} = t ] ; then
-         if [ "${annot_CMOR_LLNL[i]:n:1}" = '.' ] ; then
-           if [ "${annot_CMOR_LLNL[i]:n:2}" = '. ' ] ; then
-              flag_txt="${flag_txt}CAPT-ENDTXT-BEG"
-              isTxt=t
-              isFirst=f
-              continue
-           fi
-         fi
-       else
-         if [ "${annot_CMOR_LLNL[i]:n:1}" = '.' ] ; then
-           if [ "${annot_CMOR_LLNL[i]:n:2}" = '. ' ] ; then
-              flag_txt="${flag_txt};"
-              continue
-           fi
-         fi
-       fi
-
-       flag_txt="${flag_txt}${annot_CMOR_LLNL[i]:n:1}"
-     done
-
-     flag_txt="${flag_txt}${annot_CMOR_LLNL[i]:sz:1}"
-
-     if [ ${isTxt} = t ] ; then
-       flag_txt="${flag_txt}TXT-END"
-     else
-       flag_txt="${flag_txt}CAPT-END"
-     fi
-
-#     flag_txt="${flag_txt}${annot_CMOR_LLNL[i]}"
-     flag_txt="${flag_txt}FLAG-END"
-
-     ans="${ans}${flag_txt}"
-  done
-
-  return 0
-}
-
 ##//! THE QA of a netCDF file
 
 runQA()
@@ -1100,12 +1037,13 @@ run()
   # read output of the run
   ans=$(<out_${name}.txt)
 
-  # run CMOR3 (D.Nadeau, LLNL)
+  # run CMOR (D.Nadeau, LLNL)
   if [ ${RUN_CMOR3_LLNL} ] ; then
     declare -a annot_CMOR_LLNL
 
-    run_CMOR3_LLNL
-    convertCMOR_out2QA
+
+    # streams into ans
+    run_CMOR_LLNL
   fi
 
 #trace \
@@ -1115,19 +1053,25 @@ run()
   test ${LOG_CPU_TIME:-f} = t && logTime $realTime $cpuTime $status
 }
 
-run_CMOR3_LLNL()
+run_CMOR_LLNL()
 {
-  if ! . $QA_SRC/scripts/parseConfigFile CONDA_FOR_CMOR3 ; then
-    return
-  elif ! . $QA_SRC/scripts/parseConfigFile PrePARE ; then
-    return
+  if ! . $QA_SRC/scripts/parseConfigFile PrePARE ; then
+    echo "PrePARE=${PrePARE}  not found"
+    signalParent TERM
+    exit 1
   fi
 
   export PATH=${PrePARE%/*}:${PATH}
 
-  source ${CONDA_FOR_CMOR3}/envs/cmor/bin/activate cmor &> /dev/null
+  source ${PrePARE%/*}/bin/activate cmor &> /dev/null
 
-  export UDUNITS2_XML_PATH=${CONDA_FOR_CMOR3}/envs/cmor/share/udunits/udunits2.xml
+  if . $QA_SRC/scripts/parseConfigFile UDUNITS2_XML_PATH ; then
+    export UDUNITS2_XML_PATH
+  else
+    echo "UDUNITS2_XML_PATH=${UDUNITS2_XML_PATH}  not found"
+    signalParent TERM
+    exit 1
+  fi
 
   local file table_path
 
@@ -1159,68 +1103,42 @@ run_CMOR3_LLNL()
     mip_table=${table_path}/CMIP6_${x_fname[1]}.json
 
     if ! ls ${mip_table} &> /dev/null ; then
-       if [ -c "$TTY" ] ; then
-         echo 'Invalid MIP Table in filename and attributes'
-         echo 'Cancel CMOR3_LLN run'
-         return 1
-       fi
+#       if [ -c "$TTY" ] ; then
+         echo 'Invalid MIP Table in filename and attributes' # > $TTY
+         echo 'Cancel CMOR_LLN run' # > $TTY
+#       else
+#       fi
+       return 1
     fi
   fi
 
-  local i j line lines out
-  out="$(python $PrePARE \
-                        ${mip_table} \
-                        ${file} \
-                        2>&1 | cat -E )"
+  local ans2
+  ans2="$( python $PrePARE \
+     ${mip_table} \
+     ${file} 2>&1 \
+     | python ${QA_SRC}/scripts/python/qa-dkrz/convertPipedCMOR_output.py )"
 
-  source ${CONDA_FOR_CMOR3}/envs/cmor/bin/deactivate &> /dev/null
+  source ${PrePARE%/*}/deactivate &> /dev/null
 
-  local blk_on=f
-
-  j=0
-  for(( i=0 ; i < ${#out} ; ++i )) ; do
-    if [ "${out:i:1}" = '$' ] ; then
-      j=$((j+1))
-    else
-      lines[j]="${lines[j]}${out:i:1}"
-    fi
-  done
-
-  j=0
-  blk_on=f
-
-  for(( i=0 ; i < ${#lines[*]} ; ++i )) ; do
-    line="${lines[i]//\"/}"
-    test "${line}" = '' && continue
-
-    if [ $(expr match "${line}" '[^!]*!\+') -gt 5 ] ; then
-      if [ ${blk_on} = f ] ; then
-        blk_on=t
+  local i
+  local on=f
+  for(( i=0 ; i < ${#ans2} ; ++i )) ; do
+    if [ "${ans2:i:1}" = '"' ] ; then
+      if [ $on = f ] ; then
+        on=t
+        ans="${ans}<"
       else
-        blk_on=f
-        j=$((j+1))
+         ans="${ans}>"
+        on=f
       fi
-
-      continue
-    fi
-
-    if [ ${blk_on} = t ] ; then
-      if [ $(expr match "${line}" '^[[:space:]]*![[:space:]]*$') -eq 0 ] ; then
-        # clear the beginning
-        for(( start=1 ; start < ${#line} ; ++start )) ; do
-          test "${line:start:1}" = '!' && continue
-          test "${line:start:1}" = ' ' && continue
-
-          break
-        done
-
-        annot_CMOR_LLNL[j]="${annot_CMOR_LLNL[j]} ${line:start}"
-      fi
+    else
+      ans="${ans}${ans2:i:1}"
     fi
   done
 
   return 0
 }
+
 ##//!Send annotations to the list of email recipients.
 
 sendEMail()
@@ -1434,7 +1352,7 @@ set_qa_par()
    par=${par}"${s}"aMDR=${APPLY_MAXIMUM_DATE_RANGE}
  fi
 
- if [ ${CHECK_MODE:-f} != f ] ; then
+ if [ ${CHECK_MODE:-f} != f -a ${CHECK_MODE:-f} != t ] ; then
    par=${par}"${s}"cM=${CHECK_MODE[0]}
    for(( i=1 ; i < ${#CHECK_MODE[*]} ; ++i )) ; do
      par=${par}",${CHECK_MODE[i]}"
