QA runs CMOR3 (D. Nadeau, LLNL): refinements

diff --git a/scripts/qa-dkrz b/scripts/qa-dkrz
--- a/scripts/qa-dkrz
+++ b/scripts/qa-dkrz
@@ -1533,12 +1533,34 @@ getHomePath()
 {
   setKWL CONFIG_FILE=~/.qa-dkrz/config.txt
 
-  # where all the work is going to take place
-  if ! . $QA_SRC/scripts/parseConfigFile QA_HOME ; then
-     QA_HOME=~/.qa-dkrz
-  fi
+  # path to the current user's home
+  export QA_HOME
 
-  setKWL QA_HOME=$QA_HOME
+  if [ "${QA_HOME}" ] ; then
+    # if it is a new path, then adjust the config file
+    . $QA_SRC/scripts/parseConfigFile QA_HOME=${QA_HOME}
+  else
+    # take QA_HOME from the config file, if it exists.
+    if ! . $QA_SRC/scripts/parseConfigFile QA_HOME ; then
+      echo -e "\nPlease, specify QA_HOME [default: ${QA_SRC}/HOME/.qa-dkrz], " > ${TTY}
+      read -p "the spot for external tables and programs: " QA_HOME 2> ${TTY}
+
+      test ! ${QA_HOME} && QA_HOME=${HOME}/.qa-dkrz
+
+      if mkdir -p ${QA_HOME} &> /dev/null ; then
+        . $QA_SRC/scripts/parseConfigFile QA_HOME=${QA_HOME}
+      else
+        echo  "could not mkdir QA_HOME=${QA_HOME}"
+        exit 1
+     fi
+    fi
+
+    if [ ! -w $QA_HOME ] ; then
+      echo "directory $QA_HOME without write permissions,"
+      echo "please, restart with added option --qa-home=path"
+      exit 1
+    fi
+  fi
 
   return
 }
@@ -2521,9 +2543,9 @@ getQA_SRC()
   # extract the path to the root of the QA package
 
   # is it in a conda built?
-  local x_conda=${0%/qa-dkrz}
-  if [ ${x_conda##*/} = bin ] ; then
-    x_conda=${x_conda%/bin}
+  local x_conda=${0%/qa-dkrz/scripts/qa-dkrz}
+  if [ ${x_conda##*/} = opt ] ; then
+    x_conda=${x_conda%/opt}
     if [ -d $x_conda/opt/qa-dkrz ] ; then
        setKWL CONDA_ENV=t
        setKWL QA_SRC=$x_conda/opt/qa-dkrz
@@ -2687,12 +2709,6 @@ init()
   NO_STATUS=f
   isTPUT=f
 
-  export uCF_blkBeg
-  export uCF_blkEnd
-
-  declare -a uCF_lines
-  export uCF_lines
-
   # sets: CONDA_ENV, QA_SRC
   getQA_SRC $0
 
@@ -2803,7 +2819,7 @@ init()
   fi
 
   # package update requested and required?
-  if [ ${CONDA_ENV:-f} = f -a ${UPDATE:-enable} = enable ] ; then
+  if [ ${UPDATE:-enable} = enable ] ; then
     # checksum of current qa-dkrz
     local md5_0
     md5_0=$( md5sum ${QA_SRC}/scripts/qa-dkrz | awk '{print $1}' )
@@ -2904,13 +2920,29 @@ init()
 
 #  set -f
   # read ~/.qa-dkrz/conf-.txt for the current revision of tha package
-  . $QA_SRC/scripts/parseConfigFile QA_REVISION
+  . $QA_SRC/scripts/parseConfigFile --force_reading QA_REVISION
 
   maxNumExecThreads=0
   local nET
   for nET in ${NUM_EXEC_THREADS[*]} ; do
     maxNumExecThreads=$(( maxNumExecThreads + nET ))
   done
+
+  # a file qa_fName.nc is only created, if check_mode includes 'time' or 'data'. Only
+  # then, the QA distinguishes files which have already been checked from those
+  # which have to be checked now.
+  if [ ${CLEAR:-f} != t -a "${CHECK_MODE:-f}" != f ] ; then
+     local chmo chmos isDT
+     chmos=( ${CHECK_MODE//,/ } )
+     isDT=t
+     for chmo in ${chmos[*]} ; do
+       if [ ${chmo} = TIME -o ${chmo} = DATA ] ; then
+          isDT=f
+          break
+       fi
+     done
+     test ${isDT} = t && CLEAR=t
+  fi
 
   if [ "${SHOW_CLEAR}" ] ; then
     # precedence of any CLEAR assignment
@@ -4392,7 +4424,9 @@ summary_detectType()
   local qa_res=$1
   local logFName=${2%.log}
 
-  if ls ${qa_res}/Annotations/*.json &> /dev/null ; then
+  if ! ls ${qa_res}/Annotations/* &> /dev/null ; then
+    return 0
+  elif ls ${qa_res}/Annotations/*.json &> /dev/null ; then
     return 0
   fi
 
